module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/tests'],
  testMatch: [
    '**/__tests__/**/*.ts',
    '**/?(*.)+(spec|test).ts',
  ],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/index.ts',
    '!src/**/__tests__/**',
    '!src/**/*.test.ts',
    '!src/**/*.spec.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@shared/(.*)$': '<rootDir>/src/modules/shared/$1',
    '^@shared/domain/(.*)$': '<rootDir>/src/modules/shared/domain/$1',
    '^@shared/application/(.*)$': '<rootDir>/src/modules/shared/application/$1',
    '^@shared/infrastructure/(.*)$': '<rootDir>/src/modules/shared/infrastructure/$1',
    '^@document-processing/(.*)$': '<rootDir>/src/modules/document-processing/$1',
    '^@document-processing/domain/(.*)$': '<rootDir>/src/modules/document-processing/domain/$1',
    '^@document-processing/application/(.*)$': '<rootDir>/src/modules/document-processing/application/$1',
    '^@document-processing/infrastructure/(.*)$': '<rootDir>/src/modules/document-processing/infrastructure/$1',
    '^@document-processing/presentation/(.*)$': '<rootDir>/src/modules/document-processing/presentation/$1',
    '^@health/(.*)$': '<rootDir>/src/modules/health/$1',
  },
  testTimeout: 10000,
  verbose: true,
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
  forceExit: true,
  detectOpenHandles: false,
};
